name: CI/CD - NodeJS Demo App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: nodejs-demo-app   # run npm install inside app folder

      - name: Build Docker image
        run: docker build -t mohammadrafeeq7095/nodejs-demo-app:latest .
        working-directory: nodejs-demo-app   # Dockerfile is inside this folder

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push mohammadrafeeq7095/nodejs-demo-app:latest
        working-directory: nodejs-demo-app
